ds_map_clear(global.metatags)
dsmap(global.metatags,'TITLE','Untitled')
dsmap(global.metatags,'ARTIST','Unknown')
dsmap(global.metatags,'ALBUM','Unknown album')
dsmap(global.metatags,'GENRE','Unknown genre')
dsmap(global.metatags,'DATE','0000-00-00')
dsmap(global.metatags,'TRACKNUMBER','00')
dsmap(global.metatags,'FORMAT','None')
ResetFloatText()
global.trackname=CompileFloatText(undefined)
