var f;f=global.__colfile
var str1,str2,str3,str4,str5,str6,str7,str8,str9;
ini_open(f)
str1=ini_read_string('Color','Color1','$FFFFFF')
str2=ini_read_string('Color','Color2','$FFFFFF')
str3=ini_read_string('Color','VisColBG','$FFFFFF')
str4=ini_read_string('Color','VisColFG','$FFFFFF')
str5=ini_read_string('Color','FloatCol',string(c_lime))
str6=ini_read_string('Color','FrontWinCol','$606060')
str7=ini_read_string('Color','FrontCapCol','$FFFFFF')
str8=ini_read_string('Color','FloatBGCol','$101010')
str9=ini_read_string('Color','FloatAlpha','255')

__frontmenucol=         ereal(ini_read_string('Color','MenuCol',          '$FFFFFF'))
__visbgcol=             ereal(ini_read_string('Color','VisualBGCol',      '$FFFFFF'))
__visfgcol=             ereal(ini_read_string('Color','VisualFGCol',      '$FFFFFF'))
__butplaycol=           ereal(ini_read_string('Color','PlayCol',          '$FFFFFF'))
__butstopcol=           ereal(ini_read_string('Color','StopCol',          '$FFFFFF'))
__butplayrandcol=       ereal(ini_read_string('Color','PlayRandCol',      '$FFFFFF'))
__butnextcol=           ereal(ini_read_string('Color','NextCol',          '$FFFFFF'))
__butprevcol=           ereal(ini_read_string('Color','PrevCol',          '$FFFFFF'))
__butaboutcol=          ereal(ini_read_string('Color','AboutCol',         '$FFFFFF'))
__butsettcol=           ereal(ini_read_string('Color','SettingsCol',      '$FFFFFF'))
__butpausecol=          ereal(ini_read_string('Color','PauseCol',         '$FFFFFF'))
__butalontcol=          ereal(ini_read_string('Color','AlOnTCol',         '$FFFFFF'))
__butaddmuscol=         ereal(ini_read_string('Color','AddMusCol',        '$FFFFFF'))
__butvolcol=            ereal(ini_read_string('Color','VolumeCol',        '$FFFFFF'))
__butslidecol=          ereal(ini_read_string('Color','PosSlideCol',      '$FFFFFF'))
__butslidercol=         ereal(ini_read_string('Color','SliderCol',        '$FFFFFF'))
__butvisualcol=         ereal(ini_read_string('Color','VisualizeCol',     '$FFFFFF'))
__butsavelistcol=       ereal(ini_read_string('Color','SaveListCol',      '$FFFFFF'))
__butloadlistcol=       ereal(ini_read_string('Color','LoadListCol',      '$FFFFFF'))
__butloopcol=           ereal(ini_read_string('Color','LoopCol',          '$FFFFFF'))
__minibutton1col=       ereal(ini_read_string('Color','Mini1Col',         '$FFFFFF'))
__minibutton2col=       ereal(ini_read_string('Color','Mini2Col',         '$FFFFFF'))
__minibutton3col=       ereal(ini_read_string('Color','Mini3Col',         '$FFFFFF'))
__floatfgcol=           ereal(ini_read_string('Color','FloatFGSpriteCol', '$FFFFFF'))
__floatbgcol=           ereal(ini_read_string('Color','FloatBGSpriteCol', '$FFFFFF'))
__butsortcol=           ereal(ini_read_string('Color','FloatBGSpriteCol', '$FFFFFF'))
__bgcol=                ereal(ini_read_string('Color','BGSpriteCol',      '$FFFFFF'))

global.color1=ereal(str1)
global.color2=ereal(str2)
global.visbgcol=ereal(str3)
global.visfgcol=ereal(str4)
global.floatcolor=ereal(str5)
global.frontcol=ereal(str6)
global.captioncol=ereal(str7)
global.floatbgcol=ereal(str8)
global.floatalpha=real(string_digits(str9))/255



background_color=ereal(ini_read_string('Color','bgCol','$014426'))
ini_close()
