ini_open(global.__colfile)
global.color1=          ereal(ini_read_string('Color','Color1','$FFFFFF'))
global.color2=          ereal(ini_read_string('Color','Color2','$FFFFFF'))
global.visbgcol=        ereal(ini_read_string('Color','VisColBG','$FFFFFF'))
global.visfgcol=        ereal(ini_read_string('Color','VisColFG','$FFFFFF'))
global.floatcolor=      ereal(ini_read_string('Color','FloatCol',string(c_lime)))
global.frontcol=        ereal(ini_read_string('Color','FrontWinCol','$606060'))
global.captioncol=      ereal(ini_read_string('Color','FrontCapCol','$FFFFFF'))
global.floatbgcol=      ereal(ini_read_string('Color','FloatBGCol','$101010'))
global.floatalpha=      ereal(ini_read_string('Color','FloatAlpha','255'))/255

__frontmenucol=         ereal(ini_read_string('Color','MenuCol',          '$FFFFFF'))
__visbgcol=             ereal(ini_read_string('Color','VisualBGCol',      '$FFFFFF'))
__visfgcol=             ereal(ini_read_string('Color','VisualFGCol',      '$FFFFFF'))
__butplaycol=           ereal(ini_read_string('Color','PlayCol',          '$FFFFFF'))
__butstopcol=           ereal(ini_read_string('Color','StopCol',          '$FFFFFF'))
__butplayrandcol=       ereal(ini_read_string('Color','PlayRandCol',      '$FFFFFF'))
__butnextcol=           ereal(ini_read_string('Color','NextCol',          '$FFFFFF'))
__butprevcol=           ereal(ini_read_string('Color','PrevCol',          '$FFFFFF'))
__butaboutcol=          ereal(ini_read_string('Color','AboutCol',         '$FFFFFF'))
__butsettcol=           ereal(ini_read_string('Color','SettingsCol',      '$FFFFFF'))
__butpausecol=          ereal(ini_read_string('Color','PauseCol',         '$FFFFFF'))
__butalontcol=          ereal(ini_read_string('Color','AlOnTCol',         '$FFFFFF'))
__butaddmuscol=         ereal(ini_read_string('Color','AddMusCol',        '$FFFFFF'))
__butvolcol=            ereal(ini_read_string('Color','VolumeCol',        '$FFFFFF'))
__butslidecol=          ereal(ini_read_string('Color','PosSlideCol',      '$FFFFFF'))
__butslidercol=         ereal(ini_read_string('Color','SliderCol',        '$FFFFFF'))
__butvisualcol=         ereal(ini_read_string('Color','VisualizeCol',     '$FFFFFF'))
__butsavelistcol=       ereal(ini_read_string('Color','SaveListCol',      '$FFFFFF'))
__butloadlistcol=       ereal(ini_read_string('Color','LoadListCol',      '$FFFFFF'))
__butloopcol=           ereal(ini_read_string('Color','LoopCol',          '$FFFFFF'))
__minibutton1col=       ereal(ini_read_string('Color','Mini1Col',         '$FFFFFF'))
__minibutton2col=       ereal(ini_read_string('Color','Mini2Col',         '$FFFFFF'))
__minibutton3col=       ereal(ini_read_string('Color','Mini3Col',         '$FFFFFF'))
__floatfgcol=           ereal(ini_read_string('Color','FloatFGSpriteCol', '$FFFFFF'))
__floatbgcol=           ereal(ini_read_string('Color','FloatBGSpriteCol', '$FFFFFF'))
__butsortcol=           ereal(ini_read_string('Color','FloatBGSpriteCol', '$FFFFFF'))
__bgcol=                ereal(ini_read_string('Color','BGSpriteCol',      '$FFFFFF'))

background_color=       ereal(ini_read_string('Color','bgCol','$014426'))
ini_close()
